development:
  adapter: postgresql
  database: hey_whatever_development
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost

test:
  adapter: postgresql
  database: hey_whatever_test
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost
